### ISSUE TITLE
Running okta-awscli under zsh gives ImportError: No module named parse

### ISSUE THREAD

**Issue by calebtote** [jmhale/okta-awscli#138] opened 2020-09-16 20:25 UTC
**Describe the bug**
Running okta-awscli under zsh gives ImportError: No module named parse

**To Reproduce**
pip install okta-awscli
okta-awscli
<stacktrace>

**Expected behavior**
No stack trace

**Output**
```
Traceback (most recent call last):
  File "/Users/ctote/Library/Python/2.7/bin/okta-awscli", line 5, in <module>
    from oktaawscli.okta_awscli import main
  File "/Users/ctote/Library/Python/2.7/lib/python/site-packages/oktaawscli/okta_awscli.py", line 8, in <module>
    from oktaawscli.okta_auth import OktaAuth
  File "/Users/ctote/Library/Python/2.7/lib/python/site-packages/oktaawscli/okta_auth.py", line 9, in <module>
    from urllib.parse import parse_qs
ImportError: No module named parse
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Version of okta-awscli you're running. exits too soon

**Additional context**
This wasn't an issue, but after Mac made zsh the default shell I had to reinstall `okta-awscli` - after doing that, I now get this trace.

**Comment by jmhale** [comment] 2020-10-02 19:12
@calebtote I'm not able to reproduce this in `zsh`. 

I'm guessing that this is more related to the version of python you're running, rather than your shell, since `urllib.parse` is new in Python 3.

Can you please provide the output of: `python --version`?

**Comment by machiev** [comment] 2020-10-12 16:26
@jmhale Yes, it is related to Python version, it works with Python 3, does not with Python 2. It would be clear to mention the version in README file.

**Comment by jmhale** [comment] 2020-11-02 12:16
Added a message to the README about Python support. Closing this.

**Closed by jmhale** 2020-11-02 12:16 UTC
Labels: invalid, wontfix
